//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace AideAdmin.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entity))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserListOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLastAllotTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDicOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDicOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLoginLogByLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLoginLogByLogOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckTasteTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdUserDueTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLastQuoteTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLastNewsTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddJobLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelJobLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetJobLogByUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::AideAdmin.Properties.Settings.Default.AideAdmin_localhost_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event UserLoginCompletedEventHandler UserLoginCompleted;
        
        /// <remarks/>
        public event GetUserListCompletedEventHandler GetUserListCompleted;
        
        /// <remarks/>
        public event UpdateLastAllotTimeCompletedEventHandler UpdateLastAllotTimeCompleted;
        
        /// <remarks/>
        public event UpdateUserTypeCompletedEventHandler UpdateUserTypeCompleted;
        
        /// <remarks/>
        public event DelUserCompletedEventHandler DelUserCompleted;
        
        /// <remarks/>
        public event GetDicCompletedEventHandler GetDicCompleted;
        
        /// <remarks/>
        public event UpdateDicCompletedEventHandler UpdateDicCompleted;
        
        /// <remarks/>
        public event UpdateLoginLogByLoginCompletedEventHandler UpdateLoginLogByLoginCompleted;
        
        /// <remarks/>
        public event UpdateLoginLogByLogOutCompletedEventHandler UpdateLoginLogByLogOutCompleted;
        
        /// <remarks/>
        public event CheckTasteTimeCompletedEventHandler CheckTasteTimeCompleted;
        
        /// <remarks/>
        public event UpdUserDueTimeCompletedEventHandler UpdUserDueTimeCompleted;
        
        /// <remarks/>
        public event UpdateLastQuoteTimeCompletedEventHandler UpdateLastQuoteTimeCompleted;
        
        /// <remarks/>
        public event UpdateLastNewsTimeCompletedEventHandler UpdateLastNewsTimeCompleted;
        
        /// <remarks/>
        public event AddJobLogCompletedEventHandler AddJobLogCompleted;
        
        /// <remarks/>
        public event DelJobLogCompletedEventHandler DelJobLogCompleted;
        
        /// <remarks/>
        public event GetJobLogByUserCompletedEventHandler GetJobLogByUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserResult UserLogin(User user) {
            object[] results = this.Invoke("UserLogin", new object[] {
                        user});
            return ((UserResult)(results[0]));
        }
        
        /// <remarks/>
        public void UserLoginAsync(User user) {
            this.UserLoginAsync(user, null);
        }
        
        /// <remarks/>
        public void UserLoginAsync(User user, object userState) {
            if ((this.UserLoginOperationCompleted == null)) {
                this.UserLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserLoginOperationCompleted);
            }
            this.InvokeAsync("UserLogin", new object[] {
                        user}, this.UserLoginOperationCompleted, userState);
        }
        
        private void OnUserLoginOperationCompleted(object arg) {
            if ((this.UserLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserLoginCompleted(this, new UserLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] GetUserList(int userType, int status, int due) {
            object[] results = this.Invoke("GetUserList", new object[] {
                        userType,
                        status,
                        due});
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserListAsync(int userType, int status, int due) {
            this.GetUserListAsync(userType, status, due, null);
        }
        
        /// <remarks/>
        public void GetUserListAsync(int userType, int status, int due, object userState) {
            if ((this.GetUserListOperationCompleted == null)) {
                this.GetUserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserListOperationCompleted);
            }
            this.InvokeAsync("GetUserList", new object[] {
                        userType,
                        status,
                        due}, this.GetUserListOperationCompleted, userState);
        }
        
        private void OnGetUserListOperationCompleted(object arg) {
            if ((this.GetUserListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserListCompleted(this, new GetUserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLastAllotTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateLastAllotTime(int Id) {
            object[] results = this.Invoke("UpdateLastAllotTime", new object[] {
                        Id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateLastAllotTimeAsync(int Id) {
            this.UpdateLastAllotTimeAsync(Id, null);
        }
        
        /// <remarks/>
        public void UpdateLastAllotTimeAsync(int Id, object userState) {
            if ((this.UpdateLastAllotTimeOperationCompleted == null)) {
                this.UpdateLastAllotTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLastAllotTimeOperationCompleted);
            }
            this.InvokeAsync("UpdateLastAllotTime", new object[] {
                        Id}, this.UpdateLastAllotTimeOperationCompleted, userState);
        }
        
        private void OnUpdateLastAllotTimeOperationCompleted(object arg) {
            if ((this.UpdateLastAllotTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLastAllotTimeCompleted(this, new UpdateLastAllotTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateUserType(int Id, bool sendOrder, bool query, bool news) {
            object[] results = this.Invoke("UpdateUserType", new object[] {
                        Id,
                        sendOrder,
                        query,
                        news});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserTypeAsync(int Id, bool sendOrder, bool query, bool news) {
            this.UpdateUserTypeAsync(Id, sendOrder, query, news, null);
        }
        
        /// <remarks/>
        public void UpdateUserTypeAsync(int Id, bool sendOrder, bool query, bool news, object userState) {
            if ((this.UpdateUserTypeOperationCompleted == null)) {
                this.UpdateUserTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserTypeOperationCompleted);
            }
            this.InvokeAsync("UpdateUserType", new object[] {
                        Id,
                        sendOrder,
                        query,
                        news}, this.UpdateUserTypeOperationCompleted, userState);
        }
        
        private void OnUpdateUserTypeOperationCompleted(object arg) {
            if ((this.UpdateUserTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserTypeCompleted(this, new UpdateUserTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DelUser(int Id) {
            object[] results = this.Invoke("DelUser", new object[] {
                        Id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DelUserAsync(int Id) {
            this.DelUserAsync(Id, null);
        }
        
        /// <remarks/>
        public void DelUserAsync(int Id, object userState) {
            if ((this.DelUserOperationCompleted == null)) {
                this.DelUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelUserOperationCompleted);
            }
            this.InvokeAsync("DelUser", new object[] {
                        Id}, this.DelUserOperationCompleted, userState);
        }
        
        private void OnDelUserOperationCompleted(object arg) {
            if ((this.DelUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelUserCompleted(this, new DelUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Dictionaries[] GetDic() {
            object[] results = this.Invoke("GetDic", new object[0]);
            return ((Dictionaries[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDicAsync() {
            this.GetDicAsync(null);
        }
        
        /// <remarks/>
        public void GetDicAsync(object userState) {
            if ((this.GetDicOperationCompleted == null)) {
                this.GetDicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDicOperationCompleted);
            }
            this.InvokeAsync("GetDic", new object[0], this.GetDicOperationCompleted, userState);
        }
        
        private void OnGetDicOperationCompleted(object arg) {
            if ((this.GetDicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDicCompleted(this, new GetDicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateDic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateDic(string key, string value) {
            object[] results = this.Invoke("UpdateDic", new object[] {
                        key,
                        value});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDicAsync(string key, string value) {
            this.UpdateDicAsync(key, value, null);
        }
        
        /// <remarks/>
        public void UpdateDicAsync(string key, string value, object userState) {
            if ((this.UpdateDicOperationCompleted == null)) {
                this.UpdateDicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDicOperationCompleted);
            }
            this.InvokeAsync("UpdateDic", new object[] {
                        key,
                        value}, this.UpdateDicOperationCompleted, userState);
        }
        
        private void OnUpdateDicOperationCompleted(object arg) {
            if ((this.UpdateDicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDicCompleted(this, new UpdateDicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLoginLogByLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateLoginLogByLogin(int userId) {
            object[] results = this.Invoke("UpdateLoginLogByLogin", new object[] {
                        userId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateLoginLogByLoginAsync(int userId) {
            this.UpdateLoginLogByLoginAsync(userId, null);
        }
        
        /// <remarks/>
        public void UpdateLoginLogByLoginAsync(int userId, object userState) {
            if ((this.UpdateLoginLogByLoginOperationCompleted == null)) {
                this.UpdateLoginLogByLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLoginLogByLoginOperationCompleted);
            }
            this.InvokeAsync("UpdateLoginLogByLogin", new object[] {
                        userId}, this.UpdateLoginLogByLoginOperationCompleted, userState);
        }
        
        private void OnUpdateLoginLogByLoginOperationCompleted(object arg) {
            if ((this.UpdateLoginLogByLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLoginLogByLoginCompleted(this, new UpdateLoginLogByLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLoginLogByLogOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateLoginLogByLogOut(int userId) {
            object[] results = this.Invoke("UpdateLoginLogByLogOut", new object[] {
                        userId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateLoginLogByLogOutAsync(int userId) {
            this.UpdateLoginLogByLogOutAsync(userId, null);
        }
        
        /// <remarks/>
        public void UpdateLoginLogByLogOutAsync(int userId, object userState) {
            if ((this.UpdateLoginLogByLogOutOperationCompleted == null)) {
                this.UpdateLoginLogByLogOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLoginLogByLogOutOperationCompleted);
            }
            this.InvokeAsync("UpdateLoginLogByLogOut", new object[] {
                        userId}, this.UpdateLoginLogByLogOutOperationCompleted, userState);
        }
        
        private void OnUpdateLoginLogByLogOutOperationCompleted(object arg) {
            if ((this.UpdateLoginLogByLogOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLoginLogByLogOutCompleted(this, new UpdateLoginLogByLogOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckTasteTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckTasteTime(int userId) {
            object[] results = this.Invoke("CheckTasteTime", new object[] {
                        userId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckTasteTimeAsync(int userId) {
            this.CheckTasteTimeAsync(userId, null);
        }
        
        /// <remarks/>
        public void CheckTasteTimeAsync(int userId, object userState) {
            if ((this.CheckTasteTimeOperationCompleted == null)) {
                this.CheckTasteTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckTasteTimeOperationCompleted);
            }
            this.InvokeAsync("CheckTasteTime", new object[] {
                        userId}, this.CheckTasteTimeOperationCompleted, userState);
        }
        
        private void OnCheckTasteTimeOperationCompleted(object arg) {
            if ((this.CheckTasteTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckTasteTimeCompleted(this, new CheckTasteTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdUserDueTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdUserDueTime(int id, System.DateTime dueTime) {
            object[] results = this.Invoke("UpdUserDueTime", new object[] {
                        id,
                        dueTime});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdUserDueTimeAsync(int id, System.DateTime dueTime) {
            this.UpdUserDueTimeAsync(id, dueTime, null);
        }
        
        /// <remarks/>
        public void UpdUserDueTimeAsync(int id, System.DateTime dueTime, object userState) {
            if ((this.UpdUserDueTimeOperationCompleted == null)) {
                this.UpdUserDueTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdUserDueTimeOperationCompleted);
            }
            this.InvokeAsync("UpdUserDueTime", new object[] {
                        id,
                        dueTime}, this.UpdUserDueTimeOperationCompleted, userState);
        }
        
        private void OnUpdUserDueTimeOperationCompleted(object arg) {
            if ((this.UpdUserDueTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdUserDueTimeCompleted(this, new UpdUserDueTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLastQuoteTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateLastQuoteTime(int Id) {
            object[] results = this.Invoke("UpdateLastQuoteTime", new object[] {
                        Id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateLastQuoteTimeAsync(int Id) {
            this.UpdateLastQuoteTimeAsync(Id, null);
        }
        
        /// <remarks/>
        public void UpdateLastQuoteTimeAsync(int Id, object userState) {
            if ((this.UpdateLastQuoteTimeOperationCompleted == null)) {
                this.UpdateLastQuoteTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLastQuoteTimeOperationCompleted);
            }
            this.InvokeAsync("UpdateLastQuoteTime", new object[] {
                        Id}, this.UpdateLastQuoteTimeOperationCompleted, userState);
        }
        
        private void OnUpdateLastQuoteTimeOperationCompleted(object arg) {
            if ((this.UpdateLastQuoteTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLastQuoteTimeCompleted(this, new UpdateLastQuoteTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLastNewsTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateLastNewsTime(int Id) {
            object[] results = this.Invoke("UpdateLastNewsTime", new object[] {
                        Id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateLastNewsTimeAsync(int Id) {
            this.UpdateLastNewsTimeAsync(Id, null);
        }
        
        /// <remarks/>
        public void UpdateLastNewsTimeAsync(int Id, object userState) {
            if ((this.UpdateLastNewsTimeOperationCompleted == null)) {
                this.UpdateLastNewsTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLastNewsTimeOperationCompleted);
            }
            this.InvokeAsync("UpdateLastNewsTime", new object[] {
                        Id}, this.UpdateLastNewsTimeOperationCompleted, userState);
        }
        
        private void OnUpdateLastNewsTimeOperationCompleted(object arg) {
            if ((this.UpdateLastNewsTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLastNewsTimeCompleted(this, new UpdateLastNewsTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddJobLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddJobLog(JobLog log) {
            object[] results = this.Invoke("AddJobLog", new object[] {
                        log});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddJobLogAsync(JobLog log) {
            this.AddJobLogAsync(log, null);
        }
        
        /// <remarks/>
        public void AddJobLogAsync(JobLog log, object userState) {
            if ((this.AddJobLogOperationCompleted == null)) {
                this.AddJobLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddJobLogOperationCompleted);
            }
            this.InvokeAsync("AddJobLog", new object[] {
                        log}, this.AddJobLogOperationCompleted, userState);
        }
        
        private void OnAddJobLogOperationCompleted(object arg) {
            if ((this.AddJobLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddJobLogCompleted(this, new AddJobLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelJobLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DelJobLog(int userId) {
            object[] results = this.Invoke("DelJobLog", new object[] {
                        userId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DelJobLogAsync(int userId) {
            this.DelJobLogAsync(userId, null);
        }
        
        /// <remarks/>
        public void DelJobLogAsync(int userId, object userState) {
            if ((this.DelJobLogOperationCompleted == null)) {
                this.DelJobLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelJobLogOperationCompleted);
            }
            this.InvokeAsync("DelJobLog", new object[] {
                        userId}, this.DelJobLogOperationCompleted, userState);
        }
        
        private void OnDelJobLogOperationCompleted(object arg) {
            if ((this.DelJobLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelJobLogCompleted(this, new DelJobLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetJobLogByUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public JobLog[] GetJobLogByUser(int userId) {
            object[] results = this.Invoke("GetJobLogByUser", new object[] {
                        userId});
            return ((JobLog[])(results[0]));
        }
        
        /// <remarks/>
        public void GetJobLogByUserAsync(int userId) {
            this.GetJobLogByUserAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetJobLogByUserAsync(int userId, object userState) {
            if ((this.GetJobLogByUserOperationCompleted == null)) {
                this.GetJobLogByUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetJobLogByUserOperationCompleted);
            }
            this.InvokeAsync("GetJobLogByUser", new object[] {
                        userId}, this.GetJobLogByUserOperationCompleted, userState);
        }
        
        private void OnGetJobLogByUserOperationCompleted(object arg) {
            if ((this.GetJobLogByUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetJobLogByUserCompleted(this, new GetJobLogByUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User : Entity {
        
        private int idField;
        
        private string siteNameField;
        
        private string userNameField;
        
        private string passWordField;
        
        private string companyField;
        
        private string companyIDField;
        
        private string linkInfoField;
        
        private int userTypeField;
        
        private bool sendOrderField;
        
        private bool queryField;
        
        private bool newsField;
        
        private System.Nullable<System.DateTime> dueTimeField;
        
        private int statusField;
        
        private System.Nullable<System.DateTime> lastAllotTimeField;
        
        private System.Nullable<System.DateTime> lastQuoteTimeField;
        
        private System.Nullable<System.DateTime> lastNewsTimeField;
        
        private int queryNumField;
        
        private int newsNumField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public string LinkInfo {
            get {
                return this.linkInfoField;
            }
            set {
                this.linkInfoField = value;
            }
        }
        
        /// <remarks/>
        public int UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool SendOrder {
            get {
                return this.sendOrderField;
            }
            set {
                this.sendOrderField = value;
            }
        }
        
        /// <remarks/>
        public bool Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        public bool News {
            get {
                return this.newsField;
            }
            set {
                this.newsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DueTime {
            get {
                return this.dueTimeField;
            }
            set {
                this.dueTimeField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastAllotTime {
            get {
                return this.lastAllotTimeField;
            }
            set {
                this.lastAllotTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastQuoteTime {
            get {
                return this.lastQuoteTimeField;
            }
            set {
                this.lastQuoteTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastNewsTime {
            get {
                return this.lastNewsTimeField;
            }
            set {
                this.lastNewsTimeField = value;
            }
        }
        
        /// <remarks/>
        public int QueryNum {
            get {
                return this.queryNumField;
            }
            set {
                this.queryNumField = value;
            }
        }
        
        /// <remarks/>
        public int NewsNum {
            get {
                return this.newsNumField;
            }
            set {
                this.newsNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JobLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Dictionaries))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Entity {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserResult {
        
        private bool resultField;
        
        private string messageField;
        
        private User dataField;
        
        /// <remarks/>
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public User Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class JobLog : Entity {
        
        private int idField;
        
        private System.Nullable<int> userIDField;
        
        private string jobTypeField;
        
        private System.Nullable<System.DateTime> jobTimeField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string JobType {
            get {
                return this.jobTypeField;
            }
            set {
                this.jobTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> JobTime {
            get {
                return this.jobTimeField;
            }
            set {
                this.jobTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Dictionaries : Entity {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UserLoginCompletedEventHandler(object sender, UserLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetUserListCompletedEventHandler(object sender, GetUserListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateLastAllotTimeCompletedEventHandler(object sender, UpdateLastAllotTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateLastAllotTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateLastAllotTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateUserTypeCompletedEventHandler(object sender, UpdateUserTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DelUserCompletedEventHandler(object sender, DelUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetDicCompletedEventHandler(object sender, GetDicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Dictionaries[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Dictionaries[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateDicCompletedEventHandler(object sender, UpdateDicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateLoginLogByLoginCompletedEventHandler(object sender, UpdateLoginLogByLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateLoginLogByLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateLoginLogByLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateLoginLogByLogOutCompletedEventHandler(object sender, UpdateLoginLogByLogOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateLoginLogByLogOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateLoginLogByLogOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CheckTasteTimeCompletedEventHandler(object sender, CheckTasteTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckTasteTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckTasteTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdUserDueTimeCompletedEventHandler(object sender, UpdUserDueTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdUserDueTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdUserDueTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateLastQuoteTimeCompletedEventHandler(object sender, UpdateLastQuoteTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateLastQuoteTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateLastQuoteTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateLastNewsTimeCompletedEventHandler(object sender, UpdateLastNewsTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateLastNewsTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateLastNewsTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddJobLogCompletedEventHandler(object sender, AddJobLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddJobLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddJobLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DelJobLogCompletedEventHandler(object sender, DelJobLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelJobLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelJobLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetJobLogByUserCompletedEventHandler(object sender, GetJobLogByUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetJobLogByUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetJobLogByUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JobLog[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JobLog[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591